In [5]:
# Predict future monthly revenue

import pandas as pd
import matplotlib.pyplot as plt

from sqlalchemy import create_engine

from sklearn.linear_model import LinearRegression
import numpy as np

engine = create_engine(
    "mysql+pymysql://root:@localhost:3309/ecommerce_analytics1"
)
print("Database Connected Successfully!")

Database Connected Successfully!

In [6]:
query = """
SELECT
    LEFT(o.order_purchase_timestamp,7) AS month,
    ROUND(SUM(p.payment_value),2) AS revenue
FROM orders o
JOIN payments p
ON o.order_id = p.order_id
GROUP BY month
ORDER BY month;
"""

revenue = pd.read_sql(query, engine)

revenue.head()

     month    revenue
0  2016-09     252.24
1  2016-10   59090.48
2  2016-12      19.62
3  2017-01  138488.04
4  2017-02  291908.01

In [7]:
revenue['month'] = pd.to_datetime(revenue['month'])

revenue = revenue.sort_values('month')

revenue['month_num'] = np.arange(len(revenue))

revenue.head()

       month    revenue  month_num
0 2016-09-01     252.24          0
1 2016-10-01   59090.48          1
2 2016-12-01      19.62          2
3 2017-01-01  138488.04          3
4 2017-02-01  291908.01          4

In [8]:
X = revenue[['month_num']]
y = revenue['revenue']

model = LinearRegression()

model.fit(X, y)

print("Model Trained Successfully!")

Model Trained Successfully!